### ISSUE TITLE
Make volumio installable on an already running host

### ISSUE THREAD

**Issue by arthurlutz** [volumio/Volumio-WebUI#66]
I would like to add volumio to a debian wheezy server but cannot find any documentation on how to do so. Making a clone of the repo and pointing my browser to it does not solve this. 

First error is  

```
PHP Notice:  Undefined index: HOME in /var/www/volumio/inc/config.inc on line 32
```

So I replace the corresponding line by 

```
define('ROOTPATH', '/var/www/volumio/'); //$_SERVER['HOME'] . '/' ); // default = '/'
```
Part of the interface then appears but no actions can be done. 

Thanks, the project looks great.

**Comment by ning-yu** [comment]
This is in work, Volumio 2.0 ;)

**Comment by arthurlutz** [comment]
Hi, I think it is more appropriate to close the issue when the issue has been resolved (which doesn't seem to be the case here). Or do you have a special workflow for the issues on volumio ?

**Comment by ning-yu** [comment]
I closed the issue because this change will not be made to this repo. Volumio 1.X is unfortunately very difficult to install on an existing system since it uses a custom compiled MPD and other OS tweaks. 

Although it might have sounded offhand, we are actively working on Volumio 2.0 right now, which supports install as an apt-get package. That is on a different repo.

**Comment by arthurlutz** [comment]
Good news. Release early, release often right ? Will the licence on volumio 2.0 be different ?

**Comment by ning-yu** [comment]
Looks like I have to eat my words - according to Michelangelo, Volumio2 might not be apt-get installable due to the number of OS changes...

On the plus side, we are now public! :smiley: 

https://github.com/volumio/Volumio2
